apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: usessecret
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: secretapp
    spec:
      containers:
      - name: app
        image: busybox
        command:
          - /bin/sh
          - -c
          - 'while true; do cat /etc/some/secret1.txt /etc/some/secret2.txt /etc/other/other1.txt; sleep 5; done'
        volumeMounts:
          - name: somesecret
            readOnly: true
            mountPath: /etc/some
          - name: othersecret
            readOnly: true
            mountPath: /etc/other
      volumes:
        - name: somesecret
          secret:
            secretName: somesecret
        - name: othersecret
          secret:
            secretName: othersecret
